### ISSUE TITLE
add option to disable `subsearch.log`

### ISSUE THREAD

**Issue by kmt7** [vagabondHustler/subsearch#265]
Hi, thank you for making this amazing tool

can we have an option to allow user to disable writing logs to a file `subsearch.log` in every directory?

**Comment by vagabondHustler** [comment]
Hi, no problem, glad you enjoy it.

This is something i have completely overlooked, and yes, i will add a option.

**Comment by kmt7** [comment]
thank you

**Comment by vagabondHustler** [comment]
> thank you

A pre-release [v2.26.0-rc1](https://github.com/vagabondHustler/subsearch/releases/tag/v2.26.0-rc1) is now available with the requested feature. Everything should work, otherwise let me know.

**Comment by kmt7** [comment]
work like a charm, tested on Win-11, thank you again

**Comment by vagabondHustler** [comment]
> work like a charm, tested on Win-11, thank you again for your quick update

Awesome, more than happy to help!
