### ISSUE TITLE
[REQUEST] Ability to download multiple subtitles at once

### ISSUE THREAD

**Issue by iansquenet** [vagabondHustler/subsearch#297]

**Comment by vagabondHustler** [comment]
It is possible, it should grab all the subtitles that are equal or greater than the search threshold and matches the subtitle type (hearing impaired, non hearing impaired or both). 

If 'rename best match' is enabled on .srt file should be in the same directory as the video file, the rest in a should be in a subdirectoy called subs.

If it's not doing that I would need some more information to go on.

Or do you mean multiple movies/series at once?

**Comment by iansquenet** [comment]
Finding subtitles for multiple files at once, yes :)

**Comment by vagabondHustler** [comment]
Its unlikely I will add that anytime soon. But I'm all for the feature.
