### ISSUE TITLE
[REQUEST] Delete empty sub folder

### ISSUE THREAD

**Issue by eikaramba** [vagabondHustler/subsearch#404]
a great tool, i used to use subliminal as a command in the context menu on windows, but this tool is newer and better.

however is it possible to avoid the creation of the sub folder, or delete it if empty. not sure for what it is needed.

**Comment by vagabondHustler** [comment]
Thank you for your kind words!

When subtitles are unpacked, they are automatically stored in the sub folder. If the ["Rename best match"](https://github.com/vagabondHustler/subsearch/wiki/Subsearch-Settings) option is enabled and only one subtitle file is unpacked, the sub folder may end up being empty.

I'm gonna add this as soon as possible, so the folder gets removed if it's empty, no reason to keep that folder around if it's empty.

**Comment by eikaramba** [comment]
nice, thank you. it works as expected.
