### ISSUE TITLE
[REQUEST] clean up subtitles

### ISSUE THREAD

**Issue by eikaramba** [vagabondHustler/subsearch#405]
FYI, this tool can clean up subtitles. https://github.com/icza/srtgears

maybe the source code is interesting to add this functionality to subsearch too. not high prio.

**Comment by vagabondHustler** [comment]
> FYI, this tool can clean up subtitles. https://github.com/icza/srtgears
> 
> maybe the source code is interesting to add this functionality to subsearch too. not high prio.

It has some interesting features that could be nice to have. But I don't know GO which would make it very hard for me to implement / maintain.
