### ISSUE TITLE
Error when search for "Brazilian-Portuguese" language subtitles

### ISSUE THREAD

**Issue by bilhete** [vagabondHustler/subsearch#412]
When I run executable, I get this error:
![Screenshot_312](https://user-images.githubusercontent.com/131072949/233862742-908116be-a753-463d-b838-5e237cc91dec.png)
But it only occurs when search for "Brazilian-Portuguese" language, English one works perfectly.

**Comment by vagabondHustler** [comment]
So apparently this error would show up for all the languages, but it should be fixed now, for every language.

Thanks for braining this to my attention 🙂, the new version should be available as soon as everything is compiled into a executable, <10 min if no errors occur.

**Comment by bilhete** [comment]
**Thanks so much**, working as intended now.
