### ISSUE TITLE
how to use the python script as module?

### ISSUE THREAD

**Issue by jamiekarvans** [vagabondHustler/subsearch#544]
hey, i'm trying to write a python script and would really like to use your script in it,
how to use your script as module and what are the arguments i can pass?

**Comment by vagabondHustler** [comment]
In the beginning it was meant to be easy to use as package, but I slowly dropped that to just make it work as a complete app.

But, most of the arguments that can be passed are located in src/subsearch/data, the modules `constants` and `data_classes`.

src/subsearch/utils `io_app` has some paths and the default config values that gets loaded if there is no config file or something is missing

There used to be documentation all the classes and functions, in version [2.38.0](https://github.com/vagabondHustler/subsearch/tree/v2.38.0) and below, but never kept it up to date, but might help you to understand the code better.
